insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (1, 'Japan', 'Kuroda', 26, 'Dooley Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (2, 'Indonesia', 'Karang Daye', 1274, 'Reichert LLC');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (3, 'Indonesia', 'Huilelot', 669, 'VonRueden Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (4, 'China', 'Helong', 95, 'Donnelly and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (5, 'Rwanda', 'Liantan', 622, 'Frami, Schneider and Reynolds');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (6, 'Russia', 'Burmakino', 945, 'Padberg Group');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (7, 'China', 'Changning', 622, 'Prosacco and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (8, 'Indonesia', 'Wlingi', 1083, 'Nikolaus, Kutch and Rolfson');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (9, 'Colombia', 'Santa Fe', 1380, 'Hudson and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (10, 'Philippines', 'Lapu-Lapu City', 967, 'Maggio, Schneider and Casper');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (11, 'China', 'Tanzhesi', 1163, 'Parisian, Balistreri and Gaylord');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (12, 'Philippines', 'Ondoy', 1199, 'Kuvalis, Aufderhar and Mohr');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (13, 'Mongolia', 'Mandal', 34, 'Mosciski Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (14, 'Peru', 'Tres Unidos', 714, 'Balistreri, Zulauf and Turcotte');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (15, 'China', 'Shuigou’ao', 754, 'Erdman-Heaney');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (16, 'China', 'Lishan', 1236, 'VonRueden, Corkery and Homenick');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (17, 'Democratic Republic of the Congo', 'Mushie', 333, 'Carter, Pacocha and Simonis');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (18, 'Rwanda', 'Sumbe', 146, 'Lindgren, Orn and Batz');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (19, 'Philippines', 'Maguyam', 1124, 'Hermann, Greenholt and Hahn');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (20, 'Indonesia', 'Airmata', 362, 'Waelchi LLC');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (21, 'Poland', 'Zbytków', 343, 'Green LLC');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (22, 'China', 'Gaxung', 944, 'Gleason LLC');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (23, 'France', 'Chambéry', 476, 'Mertz, Jaskolski and Goodwin');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (24, 'El Salvador', 'Quezaltepeque', 721, 'Harber and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (25, 'Indonesia', 'Cukangpanjang', 394, 'Wunsch and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (26, 'France', 'Gif-sur-Yvette', 112, 'Jacobson, Willms and Bins');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (27, 'Sweden', 'Vallentuna', 859, 'Brown, Shanahan and Strosin');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (28, 'China', 'Caohe', 363, 'Strosin Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (29, 'Indonesia', 'Gagah', 1267, 'Ebert Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (30, 'Malta', 'Ghaxaq', 534, 'Gleason, Wiza and Russel');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (31, 'Argentina', 'Corral de Bustos', 832, 'Borer Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (32, 'Portugal', 'Vila Chã de Ourique', 1140, 'Schinner, Torphy and Padberg');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (33, 'Indonesia', 'Bima', 1073, 'Mante and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (34, 'Malaysia', 'Raub', 1392, 'Bergstrom-Reichel');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (35, 'Colombia', 'Huillapima', 451, 'Lemke Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (36, 'Israel', 'Kefar Shemaryahu', 163, 'Homenick, Wyman and Abernathy');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (37, 'Indonesia', 'Batutulis', 918, 'Becker, Kiehn and Ratke');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (38, 'Russia', 'Verkhniy Avzyan', 540, 'Prosacco, Hodkiewicz and Mohr');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (39, 'Ukraine', 'Vyshhorod', 236, 'Leuschke, Hartmann and Brown');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (40, 'Poland', 'Cisiec', 1447, 'Batz-Hilpert');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (41, 'Philippines', 'Bayog', 293, 'Hegmann, Runolfsdottir and McGlynn');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (42, 'Bosnia and Herzegovina', 'Šipovo', 1421, 'Keebler, Hauck and Johns');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (43, 'Philippines', 'Irirum', 230, 'Auer-Volkman');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (44, 'Russia', 'Sergiyev Posad', 1141, 'McCullough, Schumm and Nikolaus');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (45, 'Macedonia', 'Желино', 560, 'Pacocha, Howell and Gottlieb');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (46, 'China', 'Cairima', 1106, 'Wolf, Dibbert and McCullough');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (47, 'Russia', 'Neftegorsk', 795, 'Runolfsdottir-Ortiz');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (48, 'Indonesia', 'Kuncen', 1131, 'Bernhard, Murray and Bednar');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (49, 'Mauritius', 'Quatre Bornes', 1257, 'Langworth and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (50, 'Sweden', 'Laholm', 790, 'Pagac-Murphy');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (51, 'Portugal', 'Castelo', 1324, 'Zulauf-Larson');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (52, 'Indonesia', 'Sukamaju', 477, 'Hirthe Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (53, 'Indonesia', 'Nginjen', 750, 'Stark, Konopelski and Rippin');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (54, 'New Zealand', 'Coromandel', 972, 'Padberg-Graham');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (55, 'Russia', 'Argayash', 223, 'Bayer Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (56, 'Brazil', 'Orleans', 260, 'Russel Group');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (57, 'Gambia', 'Farafenni', 40, 'Veum, Torp and Schinner');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (58, 'Syria', 'Al Mazra‘ah', 280, 'Larkin-Bednar');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (59, 'Brazil', 'Brumadinho', 58, 'Bergstrom-Altenwerth');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (60, 'Colombia', 'Mathba', 866, 'Hoeger and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (61, 'Indonesia', 'Ciguha Tengah', 358, 'Connelly, Williamson and Nienow');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (62, 'Brazil', 'Santos Dumont', 627, 'Rutherford-Feil');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (63, 'Malaysia', 'Tawau', 1356, 'Flatley, Auer and Conroy');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (64, 'Panama', 'Cusapín', 231, 'Jenkins-Halvorson');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (65, 'China', 'Yingcheng', 161, 'Runolfsdottir-Fahey');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (66, 'Philippines', 'Perrelos', 109, 'Denesik Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (67, 'Indonesia', 'Pledo', 24, 'Mertz-Pagac');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (68, 'Poland', 'Kargowa', 527, 'Flatley-Little');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (69, 'Russia', 'Pavlovsk', 1047, 'O''Kon LLC');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (70, 'China', 'Hexi', 1116, 'Volkman LLC');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (71, 'United States', 'Las Vegas', 903, 'Bergnaum-Deckow');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (72, 'Indonesia', 'Kopang Satu', 674, 'Dickinson-Kassulke');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (73, 'Tunisia', 'Jendouba', 1424, 'Schmitt, Rutherford and Ullrich');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (74, 'France', 'Courbevoie', 1159, 'Shanahan-Hilll');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (75, 'Poland', 'Wawrzeńczyce', 1467, 'Little, Pollich and Bayer');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (76, 'Portugal', 'Sande São Martinho', 112, 'Bogisich, Gleichner and Muller');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (77, 'China', 'Liudaogou', 758, 'Brakus, Bernhard and Franecki');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (78, 'Russia', 'Rodnikovskaya', 764, 'Kirlin-Beier');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (79, 'Indonesia', 'Kebonsari', 907, 'Gottlieb LLC');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (80, 'Cameroon', 'Mbouda', 571, 'Brekke-D''Amore');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (81, 'Portugal', 'Póvoa de Penela', 100, 'Wiegand Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (82, 'Indonesia', 'Pasanggrahan', 552, 'Toy-Bashirian');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (83, 'Poland', 'Nozdrzec', 127, 'Jacobi-Grady');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (84, 'China', 'Mishan', 1435, 'Morar and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (85, 'Rwanda', 'Abidjan', 66, 'Watsica, Lubowitz and Hickle');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (86, 'Brazil', 'Nova Petrópolis', 1414, 'Blanda-Moore');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (87, 'Indonesia', 'Sukorambi', 537, 'Stamm and Sons');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (88, 'Israel', 'Revava', 252, 'Gulgowski, Durgan and Walter');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (89, 'Colombia', 'Mirimire', 275, 'Ward LLC');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (90, 'Indonesia', 'Halimaung Jaya (F-3)', 1421, 'Powlowski Group');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (91, 'Mongolia', 'Höshööt', 160, 'Lueilwitz-Ullrich');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (92, 'Norfolk Island', 'Kingston', 346, 'Ryan-Carroll');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (93, 'United States', 'El Paso', 1187, 'Sporer Group');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (94, 'Colombia', 'Hai Riêng', 408, 'Morissette-Cormier');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (95, 'Indonesia', 'Kuta', 46, 'Schmidt, Jaskolski and Kuvalis');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (96, 'Bhutan', 'Tsimasham', 66, 'Conroy-Nitzsche');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (97, 'Russia', 'Kuznechnoye', 473, 'Gorczany Inc');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (98, 'Rwanda', 'Paso de Carrasco', 935, 'Heller-Lesch');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (99, 'Brazil', 'Goianira', 1172, 'Lebsack LLC');
insert into Gaard (GaardsID, Land, Region, HoeydeOverHavet, Navn) values (100, 'Ireland', 'Carrigaline', 518, 'Bayer, Olson and Blick');
