insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (1, 1965, 5, 9, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (2, 1996, 79, 64, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (3, 1990, 48, 84, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (4, 2011, 76, 41, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (5, 1995, 9, 19, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (6, 2003, 7, 31, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (7, 1989, 74, 87, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (8, 1996, 19, 23, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (9, 2006, 77, 77, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (10, 2000, 16, 34, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (11, 2009, 88, 9, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (12, 1998, 36, 16, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (13, 1993, 37, 76, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (14, 1991, 90, 66, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (15, 1993, 88, 24, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (16, 2001, 41, 53, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (17, 1998, 30, 51, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (18, 2011, 41, 74, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (19, 2002, 58, 33, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (20, 1994, 85, 92, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (21, 1996, 54, 24, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (22, 1996, 24, 17, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (23, 2000, 39, 21, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (24, 1995, 30, 82, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (25, 2010, 82, 69, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (26, 2012, 34, 38, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (27, 2000, 40, 52, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (28, 1975, 56, 42, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (29, 1997, 69, 93, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (30, 1992, 81, 17, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (31, 2001, 86, 32, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (32, 2012, 59, 40, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (33, 2007, 32, 51, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (34, 2007, 55, 29, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (35, 2005, 69, 78, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (36, 1992, 50, 25, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (37, 1995, 27, 24, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (38, 1999, 40, 20, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (39, 2011, 45, 68, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (40, 2003, 88, 23, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (41, 2006, 42, 63, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (42, 1993, 97, 88, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (43, 1999, 82, 10, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (44, 2001, 75, 34, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (45, 2001, 81, 49, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (46, 2013, 17, 17, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (47, 1986, 50, 74, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (48, 1997, 76, 59, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (49, 2000, 93, 50, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (50, 2011, 8, 40, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (51, 2003, 11, 81, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (52, 2002, 16, 64, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (53, 1994, 11, 83, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (54, 1988, 98, 5, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (55, 1998, 44, 92, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (56, 1994, 41, 30, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (57, 1998, 12, 4, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (58, 2001, 26, 90, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (59, 1993, 39, 55, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (60, 2013, 80, 38, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (61, 1997, 53, 41, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (62, 1995, 67, 76, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (63, 2003, 67, 28, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (64, 2011, 34, 87, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (65, 2008, 22, 75, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (66, 2008, 2, 85, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (67, 1993, 80, 62, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (68, 1995, 67, 11, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (69, 2011, 72, 34, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (70, 2011, 21, 5, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (71, 1986, 85, 28, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (72, 1995, 98, 1, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (73, 2001, 83, 99, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (74, 2002, 64, 46, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (75, 1977, 62, 75, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (76, 1995, 68, 69, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (77, 2003, 22, 34, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (78, 2010, 59, 84, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (79, 2006, 84, 88, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (80, 2009, 20, 2, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (81, 2001, 16, 47, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (82, 1989, 13, 49, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (83, 1993, 82, 77, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (84, 2003, 90, 15, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (85, 1999, 56, 15, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (86, 1996, 25, 24, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (87, 1967, 73, 76, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (88, 1986, 32, 11, 'Vasket');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (89, 2004, 58, 42, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (90, 2007, 47, 19, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (91, 1992, 97, 97, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (92, 2011, 52, 31, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (93, 2010, 20, 7, 'Arthur foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (94, 1991, 68, 81, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (95, 2012, 93, 41, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (96, 1991, 21, 92, 'Honning foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (97, 1997, 58, 96, 'Våt skallet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (98, 2011, 3, 72, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (99, 2012, 26, 57, 'Naturlig foredlet');
insert into Parti (PartiID, InnhoestingsAar, BetaltUSD, GaardsID, MetodeNavn) values (100, 2010, 81, 81, 'Vasket');
